-- ========================================
-- TAPSIRIQ 14: Müştəri yaş qruplarına görə satış payı
-- ========================================
SELECT CASE 
         WHEN AGE BETWEEN 18 AND 35 THEN '18-35'
         WHEN AGE BETWEEN 36 AND 50 THEN '36-50'
         WHEN AGE BETWEEN 51 AND 69 THEN '51-69'
       END AS AGE_GROUP,
       SUM(P.UNIT_PRICE * OD.QUANTITY - OD.DISCOUNT) AS TOTAL_SALES
FROM CUSTOMERS C
JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID
JOIN ORDER_DETAILS OD ON OD.ORDER_ID=O.ORDER_ID
JOIN PRODUCTS P ON P.PRODUCT_ID=OD.PRODUCT_ID
WHERE O.STATUS='Completed'
GROUP BY CASE 
           WHEN AGE BETWEEN 18 AND 35 THEN '18-35'
           WHEN AGE BETWEEN 36 AND 50 THEN '36-50'
           WHEN AGE BETWEEN 51 AND 69 THEN '51-69'
         END
ORDER BY TOTAL_SALES;