-- ========================================
-- TAPSIRIQ 15: 2023 və 2024-cü illər üzrə satış artımı
-- ========================================
SELECT TO_CHAR(TO_DATE(O.ORDER_DATE,'YYYY-MM-DD'),'YYYY') AS YEARS_2023_2024,
       SUM(P.UNIT_PRICE * OD.QUANTITY - OD.DISCOUNT) AS TOTAL_SALES
FROM ORDERS O
JOIN ORDER_DETAILS OD ON O.ORDER_ID=OD.ORDER_ID
JOIN PRODUCTS P ON P.PRODUCT_ID=OD.PRODUCT_ID
WHERE TO_CHAR(TO_DATE(ORDER_DATE,'YYYY-MM-DD'),'YYYY') IN (2023,2024)
  AND O.STATUS='Completed'
GROUP BY TO_CHAR(TO_DATE(O.ORDER_DATE