-- ========================================
-- TAPSIRIQ 3: Hər məhsul üzrə gəlir, maya dəyəri və mənfəət
-- Ən çox ziyan edən 10 məhsul
-- ========================================
SELECT P.PRODUCT_ID,
       P.COST_PRICE,
       SUM(P.UNIT_PRICE*OD.QUANTITY-OD.DISCOUNT) AS REVENUE,
       SUM((P.UNIT_PRICE*OD.QUANTITY-OD.DISCOUNT)-(P.COST_PRICE*OD.QUANTITY)) AS PROFIT
FROM ORDER_DETAILS OD
JOIN ORDERS O ON OD.ORDER_ID=O.ORDER_ID
JOIN PRODUCTS P ON OD.PRODUCT_ID=P.PRODUCT_ID
WHERE O.STATUS='Completed'
GROUP BY P.PRODUCT_ID,P.COST_PRICE
HAVING SUM((P.UNIT_PRICE*OD.QUANTITY-OD.DISCOUNT)-(P.COST_PRICE*OD.QUANTITY))<0
ORDER BY PROFIT
FETCH NEXT 10 ROWS ONLY;